projects:
  mfna:
    schemaPath: graphql/schema.json
    includes:
      - ./graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: graphql
        maxDepth: 2
extensions:
  amplify:
    version: 3
